#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 12 16:56:42 CST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ea70bbd0da3b41d38c6ab28e0fbbe4f1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_2 -L fifo_generator_v13_2_3 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cnn_tb_behav xil_defaultlib.cnn_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto ea70bbd0da3b41d38c6ab28e0fbbe4f1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L blk_mem_gen_v8_4_2 -L fifo_generator_v13_2_3 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cnn_tb_behav xil_defaultlib.cnn_tb xil_defaultlib.glbl -log elaborate.log

