#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 12 16:56:44 CST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cnn_tb_behav -key {Behavioral:sim_1:Functional:cnn_tb} -tclbatch cnn_tb.tcl -view /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sim_1/imports/minist_cnn/cnn_tb_behav.wcfg -view /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/cnn_tb_behav.wcfg -log simulate.log"
xsim cnn_tb_behav -key {Behavioral:sim_1:Functional:cnn_tb} -tclbatch cnn_tb.tcl -view /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sim_1/imports/minist_cnn/cnn_tb_behav.wcfg -view /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/cnn_tb_behav.wcfg -log simulate.log

