# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2.xci
# IP: The module: 'W_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'W_fc2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2.xci
# IP: The module: 'W_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ease/Desktop/01_JI/07_2022Fall/chips/FPGA-proj/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'W_fc2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
